routing:
  domain: mpxy.sandbox.cxcloud.com
  ssl: true
  rules:
    - path: /api/service-commerce
      serviceName: service-commerce
      servicePort: 4003
    - path: /api/content
      serviceName: service-content
      servicePort: 4003
    - path: /api/search
      serviceName: service-search
      servicePort: 4003
    - path: /
      serviceName: ui-demo-react
      servicePort: 80
